### ISSUE TITLE
All your numbers are belong to Busted

### ISSUE THREAD

**Issue by alerque** [simoncozens/cassowary.lua#6]
My "issues with Busted" as chronicled in [SILE issue 654](https://github.com/simoncozens/sile/pull/654) and [Busted issue 609](https://github.com/Olivine-Labs/busted/issues/609) actually seem to trace to the 1.1→2.0 migration in this library swapping out stdlib with penlight.

Dropping the old version of this back into place (and fixing the paths so it is actually used by Busted) lets the tests pass again.

**Comment by alerque** [comment]
It does seem like the new version works inside of SILE but returns unexpected zero values when run inside Busted.

**Comment by simoncozens** [comment]
So to summarize:

* Cassowary 2.0 busted tests work.
* Cassowary 2.0 in SILE works.
* SILE busted tests using Cassoway 1.1 work.
* SILE busted tests using Cassoway 2.0 fail.

I... don't know what to do about that. :-( Maybe we just need to lock SILE to v1.1?

**Comment by alerque** [comment]
It's worse than that.

* SILE busted tests using Cassoway 2.0 work in Travis ([results](https://travis-ci.com/alerque/sile/builds/125180338#L867)).
* SILE busted tests using Cassoway 2.0 fail on Arch Linux ([results](https://termbin.com/iptt)).

There can't be that many more variables. This is tested having configured my source tree using `./configure --without-system-luarocks` so literally the only thing changing is Cassoway and I can sit there swapping the contents of `lua_modules/share/lua/5.3/cassowary.lua` back and forth between 1.1 and 2.0 code and run the same test (`make broken` on [this test branch](https://github.com/alerque/sile/commits/test-the-tester) which has a stripped down MWE version of one of the failing tests) and it works on one set of code, fails on the other. Hence I'm pretty sure nothing else is changing, no different versions of other libraries being used between tests, etc.

**Comment by alerque** [comment]
* Cassowary 2.0 busted tests don't work on Arch Linux.

Specifically `busted tests` from a clean checkout (was there something else supposed to be used to trigger this) fails 18 tests.

```sh
+++++-+----++++--------***++++**+++++++++++-++-+++---+++++++++++++***++++
47 successes / 18 failures / 8 errors / 0 pending : 0.115291 seconds

Failure -> tests/constraint_spec.lua @ 69
works with nested expressions
tests/constraint_spec.lua:74: Expected to be truthy, but value was:
(boolean) false

Failure -> tests/constraint_spec.lua @ 83
handles inequality constructors with operator arguments
tests/constraint_spec.lua:88: Expected to be truthy, but value was:
(boolean) false

Failure -> tests/constraint_spec.lua @ 94
handles expressions with variables, operators, and numbers
tests/constraint_spec.lua:98: Expected to be truthy, but value was:
(boolean) false

Failure -> tests/constraint_spec.lua @ 104
handles inequalities with reused variables
tests/constraint_spec.lua:108: Expected to be truthy, but value was:
(boolean) false

Failure -> tests/end_to_end_spec.lua @ 6
End-To-End simple1
tests/end_to_end_spec.lua:14: Expected objects to be equal.
Passed in:
(number) 2
Expected:
(number) 0

Failure -> tests/end_to_end_spec.lua @ 62
End-To-End exp >= num
tests/end_to_end_spec.lua:78: Expected objects to be the same.
Passed in:
(number) 90
Expected:
(number) 10

Failure -> tests/end_to_end_spec.lua @ 82
End-To-End num <= exp
tests/end_to_end_spec.lua:94: Expected objects to be the same.
Passed in:
(number) 90
Expected:
(number) 10

Failure -> tests/end_to_end_spec.lua @ 98
End-To-End exp == var
tests/end_to_end_spec.lua:111: Expected objects to be the same.
Passed in:
(number) 90
Expected:
(number) 10

Failure -> tests/end_to_end_spec.lua @ 115
End-To-End exp >= var
tests/end_to_end_spec.lua:128: Expected objects to be the same.
Passed in:
(number) 90
Expected:
(number) 10

Failure -> tests/end_to_end_spec.lua @ 132
End-To-End local <= exp
tests/end_to_end_spec.lua:144: Expected objects to be the same.
Passed in:
(number) 90
Expected:
(number) 10

Failure -> tests/end_to_end_spec.lua @ 148
End-To-End exp == exp
tests/end_to_end_spec.lua:164: Expected objects to be the same.
Passed in:
(number) 100
Expected:
(number) 10

Failure -> tests/end_to_end_spec.lua @ 170
End-To-End exp >= exp
tests/end_to_end_spec.lua:186: Expected objects to be the same.
Passed in:
(number) 100
Expected:
(number) 10

Failure -> tests/end_to_end_spec.lua @ 189
End-To-End exp <= exp
tests/end_to_end_spec.lua:207: Expected objects to be the same.
Passed in:
(number) 100
Expected:
(number) 10

Failure -> tests/expression_spec.lua @ 67
clone
tests/expression_spec.lua:74: Expected objects to be the same.
Passed in:
(nil)
Expected:
(number) 20

Failure -> tests/expression_spec.lua @ 96
times
tests/expression_spec.lua:103: Expected objects to be the same.
Passed in:
(number) 200
Expected:
(nil)

Failure -> tests/expression_spec.lua @ 173
plus
tests/expression_spec.lua:184: Expected objects to be the same.
Passed in:
(number) 20
Expected:
(nil)

Failure -> tests/expression_spec.lua @ 188
minus
tests/expression_spec.lua:199: Expected objects to be the same.
Passed in:
(number) 20
Expected:
(nil)

Failure -> tests/expression_spec.lua @ 203
divide
tests/expression_spec.lua:213: Expected objects to be the same.
Passed in:
(number) 10
Expected:
(nil)

Error -> tests/end_to_end_spec.lua @ 210
End-To-End addDelete1
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary

Error -> tests/end_to_end_spec.lua @ 238
End-To-End addDelete2
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary

Error -> tests/end_to_end_spec.lua @ 270
End-To-End casso1
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary

Error -> tests/end_to_end_spec.lua @ 335
End-To-End multiedit
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary

Error -> tests/end_to_end_spec.lua @ 379
End-To-End multiedit2
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary

Error -> tests/simplexsolver_spec.lua @ 11
addEditVar works with required strength
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary

Error -> tests/simplexsolver_spec.lua @ 23
addEditVar works with required strength after many suggestions
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary

Error -> tests/simplexsolver_spec.lua @ 42
addEditVar works with weight
/usr/share/lua/5.3/cassowary.lua:1142: InternalError: An error has occured in Cassowary
```

**Comment by alerque** [comment]
* Cassowary 1.1 busted tests don't work on Arch Linux.

Both the v1.1 and v2.0 tags fail 19 busted tests. The post v2.0 commit that "fix tests" fails just 18 of them (one having been commented out).

**Comment by alerque** [comment]
Given that Cassowary is the only thing using Penlight's `tablex.deepcopy` in the SILE dependency tree, I'm guessing this issue is a 1 to 1 peer of [SILE issue 662](https://github.com/simoncozens/sile/issues/662) and the difference between my system and yours is our version of Penlight.

**Comment by alerque** [comment]
This is narrowed down to [this copy operation](https://github.com/simoncozens/cassowary.lua/blob/master/cassowary.lua#L303) not being able to use [the updated deepcopy](https://github.com/stevedonovan/Penlight/commit/967ed9b99f9a99910ac0ade8ab0383834666f2dc#diff-0c81a5acc3431ace2d74e523139aff27L103)
